#Ingame commands do not change the config!
templates:
  explosions: "[@tick:@order] @amount @type at x:@x@vx y:@y@vy z:@z@vz"
  stacking: "[@tick:@order] @amount @type stacked at x:@x@vx y:@y@vy z:@z@vz"
  nearby: "Entity near power: x:@x@vx y:@y@vy z:@z@vz d:@d@vd"
  entityspawn: "[@tick] @type spawned at x:@x y:@y z:@z"
protection:
  enable: true
  not_protected:
    - Cobblestone
    - Sand
    - Gravel
    - Step